### ISSUE TITLE
 No src/posts folder found at...

### ISSUE THREAD

**Issue by ladyofcode** [PritishMishraa/hashnode-publish-action#1]
Hello! Thanks for creating this - hopefully it'll make cross-posting easier.

I've encountered the following error in the Actions log and would appreciate some assistance:

> No src/posts folder found at /home/runner/work/_actions/PritishMishraa/hashnode-publish-action/v1.0.2/src/posts.

How would I go about addressing it? My .yml file contains the following:

```
name: Publish to Hashnode

on:
  push:
    branches:
      - master
    paths:
      - 'src/posts/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Hashnode
        uses: PritishMishraa/hashnode-publish-action@v1.0.2
        with:
          src: 'src/posts/'
          HASHNODE_PAT: ${{ secrets.HASHNODE_PAT }}
```
