### ISSUE TITLE
General workflow

### ISSUE THREAD

**Issue by defersec** [PritishMishraa/hashnode-publish-action#2]
Hi! I wanted to setup automatic publishing of blog posts via your Github Action. This is what I have: 

- `.github/workflows/publish-to-hashnode.yaml` 

```
name: Publish to Hashnode
on:
  push:
    branches:
      - main
    paths:
      - 'blogs/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Publish to Hashnode
        uses: PritishMishraa/hashnode-publish-action@v1.0.2
        with:
          src: blogs
          HASHNODE_PAT: ${{ secrets.HASHNODE_PAT }}
      - name: (AUTO COMMIT) Commit and Push changes
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I have added my hashnode personal access token to the repository's secrets & variables. In `blogs/` I have commited a file with this content: 

```
---
title: My first post using Github as source
subtitle: An example subtitle
slug: post-from-github-as-source
tags: reactjs, css, python, nodejs
cover: https://cdn.hashnode.com/res/hashnode/image/upload/v1649662225945/7f_c6UxhR.jpg?auto=compress
domain: defersec.com
saveAsDraft: true
---

# Some introduction

Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has
been the industry's standard dummy text ever since the 1500s, when an unknown printer took
a galley of type and scrambled it to make a type specimen book. It has survived not only
five centuries, but also the leap into electronic typesetting, remaining essentially
unchanged. It was popularised in the 1960s with the release of Letraset sheets containing
Lorem Ipsum passages, and more recently with desktop publishing software like Aldus
PageMaker including versions of Lorem Ipsum.

asdasdkjh

# Why do we use it?

It is a long established fact that a reader will be distracted by the readable content of
a page when looking at its layout. The point of using Lorem Ipsum is that it has a
more-or-less normal distribution of letters, as opposed to using 'Content here, content
here', making it look like readable English. Many desktop publishing packages and web page
editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum'
will uncover many web sites still in their infancy. Various versions have evolved over the
years, sometimes by accident, sometimes on purpose (injected humour and the like).
```

When I push the file the github actions triggers, however, I get following message (in the "Publish to Hashnode" stept): 

```
Run PritishMishraa/hashnode-publish-action@v1.0.2
  with:
    src: blogs
    HASHNODE_PAT: ***
  
No blog posts to publish.
```

Do you have any ideas why? Thanks for making this action publicly available. 

KR, 
DeferSec
